## Numpy array and basics

In [1]:
import numpy as np
import time

### creating array from list

In [2]:
arr_1d = np.array([1,2,3,4])
print("1D array : ",arr_1d)
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : \n",array_2d)

1D array :  [1 2 3 4]
2D array : 
 [[1 2 3]
 [4 5 6]]


##List vs Numpy

In [3]:
py_list = [1,2,3,4]
print(f"Python list : {py_list*5} ")
numpy_arr = np.array(py_list)
print("Numpy array : ",numpy_arr*5)

Python list : [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4] 
Numpy array :  [ 5 10 15 20]


In [4]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Time taken to create Python list : ",time.time()-start)
start = time.time()
numpy_list = np.arange(1000000)*2
print("Time taken to create Numpy array : ",time.time()-start)

Time taken to create Python list :  0.04882311820983887
Time taken to create Numpy array :  0.003947257995605469


## Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("Array of zeros : \n",zeros)
ones = np.ones((2,3))  
print("Array of ones : \n",ones)
full = np.full((2,2),7)
print("Array filled with 7 : \n",full)
random = np.random.random((3,3))
print("Array of random numbers : \n",random)

seqence = np.arange(0,10,2)
print("Sequence of numbers from 0 to 10 with step 2 : ",seqence)

Array of zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of ones : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Array filled with 7 : 
 [[7 7]
 [7 7]]
Array of random numbers : 
 [[0.95437278 0.65707547 0.47125127]
 [0.41558046 0.3905839  0.64818617]
 [0.86796851 0.5337187  0.67796949]]
Sequence of numbers from 0 to 10 with step 2 :  [0 2 4 6 8]


## Vector, Matrix and Tensor

In [6]:
vector = np.array([1,2,3])
print("Vector : ",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor : \n",tensor)

Vector :  [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properrties

In [7]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print("Shape ",arr.shape)
print("Size ",arr.size)
print("Dimensions ",arr.ndim)
print("DType ",arr.dtype)

Shape  (2, 5)
Size  10
Dimensions  2
DType  int64


### Array Reshaping

In [8]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array ",reshaped)

flattened = reshaped.flatten()
print("Flattened array ",flattened)

# Returns view instead of copy
revaled = reshaped.ravel()
print("Raveled array ",revaled)

#Transpose
transpose = reshaped.T
print("Transposed array : \n",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
